name: QA

on: push

jobs:
  run_qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ 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 }}
      - run: ./test/run-qa.sh
        timeout-minutes: 5
    services:
      sonarqube:
        image: sonarqube:8.9-community
        ports:
          - 9000:9000
